import Head from "next/head";
import Header from "../components/Header";
import AssetGrid from "../components/AssetGrid";
import LiabilityGrid from "../components/LiabilityGrid";

import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { collection, addDoc } from "firebase/firestore";
import { getDocs } from "firebase/firestore";
import { Button } from "@mui/material";
import React, { useEffect } from "react";

const firebaseConfig = {
  //shhh
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Cloud Firestore and get a reference to the service
const db = getFirestore(app);

async function testA() {
  try {
    const docRef = await addDoc(collection(db, "assets"), {
      date_added: "1672581257797",
      name: "testAssets",
      owner_id: "C8rZzRZsNIAhneQAY9jI",
      value: "150928.33",
    });
    console.log("Document written with ID: ", docRef.id);
  } catch (e) {
    console.error("Error adding document: ", e);
  }
}

async function testL() {
  try {
    const docRef = await addDoc(collection(db, "liabilities"), {
      date_added: "1672581257797",
      name: "testLiability",
      owner_id: "C8rZzRZsNIAhneQAY9jI",
      value: "67928.33",
    });
    console.log("Document written with ID: ", docRef.id);
  } catch (e) {
    console.error("Error adding document: ", e);
  }
}

export default function Home() {
  const [assets, setAssets] = React.useState(false);
  const [liabilities, setLiabilities] = React.useState(false);

  async function getAssets() {
    let assets = Array();
    const querySnapshot = await getDocs(collection(db, "assets"));
    querySnapshot.forEach((doc) => {
      let asset = doc.data();
      asset.id = doc.id;
      assets.push(asset);
    });
    setAssets(assets);
  }

  async function getLiabilities() {
    let liabilities = Array();
    const querySnapshot = await getDocs(collection(db, "liabilities"));
    querySnapshot.forEach((doc) => {
      let liability = doc.data();
      liability.id = doc.id;
      liabilities.push(liability);
    });
    setLiabilities(liabilities);
  }

  useEffect(() => {
    getAssets();
    getLiabilities();
  });

  return (
    <>
      <Head>
        <title>swealth | Own your finances</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ marginTop: "20px", marginLeft: "20px" }}>
          <Header />
        </div>
        <body>
          <header>
            <div>
              <div
                style={{
                  textAlign: "center",
                  fontSize: "6em",
                  marginTop: "100px",
                }}
              >
                £1,298,333
              </div>
              <div
                style={{
                  textAlign: "center",
                  color: "#84928b",
                  fontSize: "1em",
                  fontStyle: "italic",
                }}
              >
                NET WORTH
              </div>
              <hr
                color="#3e3e3e"
                style={{
                  marginLeft: "10%",
                  marginRight: "10%",
                  marginTop: "50px",
                }}
              />
              <div
                className="parent"
                style={{
                  textAlign: "center",
                  marginTop: "75px",
                }}
              >
                <div className="assetTitle">
                  <div
                    style={{
                      textAlign: "center",
                      fontSize: "4em",
                    }}
                  >
                    £1,928,929
                  </div>
                  <div
                    style={{
                      textAlign: "center",
                      color: "#84928b",
                      fontSize: ".8em",
                      fontStyle: "italic",
                    }}
                  >
                    ASSETS
                  </div>
                </div>
                <div
                  className="assetGrid"
                  style={{ marginLeft: "150px", marginRight: "150px" }}
                >
                  <Button onClick={testA}>Add</Button>
                  <AssetGrid assets={assets} />
                </div>
                <div className="liabilityTitle">
                  <div
                    style={{
                      textAlign: "center",
                      fontSize: "4em",
                    }}
                  >
                    £630,596
                  </div>
                  <div
                    style={{
                      textAlign: "center",
                      color: "#84928b",
                      fontSize: ".8em",
                      fontStyle: "italic",
                    }}
                  >
                    LIABILITIES
                  </div>
                </div>
                <div
                  className="liabilityGrid"
                  style={{ marginLeft: "150px", marginRight: "150px" }}
                >
                  <Button onClick={testL}>Add</Button>
                  <LiabilityGrid liabilities={liabilities} />
                </div>
              </div>
            </div>
          </header>
        </body>
      </main>
    </>
  );
}
