import Head from "next/head";
import Header from "../components/Header";
import AssetGrid from "../components/AssetGrid";
import LiabilityGrid from "../components/LiabilityGrid";

const {
  initializeApp,
  applicationDefault,
  cert,
} = require("firebase-admin/app");
const {
  getFirestore,
  Timestamp,
  FieldValue,
} = require("firebase-admin/firestore");

export default function Home() {
  return (
    <>
      <Head>
        <title>swealth | Own your finances</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ marginTop: "20px", marginLeft: "20px" }}>
          <Header />
        </div>
        <body>
          <header>
            <div>
              <div
                style={{
                  textAlign: "center",
                  fontSize: "6em",
                  marginTop: "100px",
                }}
              >
                £1,298,333
              </div>
              <div
                style={{
                  textAlign: "center",
                  color: "#84928b",
                  fontSize: "1em",
                  fontStyle: "italic",
                }}
              >
                NET WORTH
              </div>
              <hr
                color="#3e3e3e"
                style={{
                  marginLeft: "10%",
                  marginRight: "10%",
                  marginTop: "50px",
                }}
              />
              <div
                className="parent"
                style={{
                  textAlign: "center",
                  marginTop: "75px",
                }}
              >
                <div className="assetTitle">
                  <div
                    style={{
                      textAlign: "center",
                      fontSize: "4em",
                    }}
                  >
                    £1,928,929
                  </div>
                  <div
                    style={{
                      textAlign: "center",
                      color: "#84928b",
                      fontSize: ".8em",
                      fontStyle: "italic",
                    }}
                  >
                    ASSETS
                  </div>
                </div>
                <div
                  className="assetGrid"
                  style={{ marginLeft: "150px", marginRight: "150px" }}
                >
                  <AssetGrid />
                </div>
                <div className="liabilityTitle">
                  <div
                    style={{
                      textAlign: "center",
                      fontSize: "4em",
                    }}
                  >
                    £630,596
                  </div>
                  <div
                    style={{
                      textAlign: "center",
                      color: "#84928b",
                      fontSize: ".8em",
                      fontStyle: "italic",
                    }}
                  >
                    LIABILITIES
                  </div>
                </div>
                <div
                  className="liabilityGrid"
                  style={{ marginLeft: "150px", marginRight: "150px" }}
                >
                  <LiabilityGrid />
                </div>
              </div>
            </div>
          </header>
        </body>
      </main>
    </>
  );
}
